### ISSUE TITLE
Missing MySQL String

### ISSUE THREAD

**Issue by NicoMax2012** [kanersps/esplugin_mysql#12]
[ERROR] [MySQL] [esplugin_mysql] An error happens on MySQL for query "UPDATE users SET `roles`='Admin|Dev' WHERE `identifier`='steam:xxxxxxxxxxxx'": ER_BAD_FIELD_ERROR: Unknown column 'roles' in 'field list'

Somebody know to solve this? The original SQL doens´t have a table with roles

**Comment by kanersps** [comment]
You can just create the table


________________________________

**Comment by NicoMax2012** [comment]
as varchar?
