### ISSUE TITLE
Data does not register to the database

### ISSUE THREAD

**Issue by EltsuDEV** [kanersps/esplugin_mysql#13]
![Huomautus 2020-01-18 205638](https://user-images.githubusercontent.com/36920086/72668984-05034700-3a35-11ea-9eee-332351f9c983.png)
Hey!

My esx server players and they data does not register in the "users" database?

I have working esx_skin and skinchanger systems but anything will not load in database.

I need fast help.

**Comment by ghost** [comment]
Same here .. nothing stored in database

![Unbenannt-1](https://user-images.githubusercontent.com/61034304/74495474-3eb25b00-4ed8-11ea-9248-8046353193ee.png)

**Comment by MaxTexFcX** [comment]
I had a same problem
