### ISSUE TITLE
Bank and Money does not hook correctly.

### ISSUE THREAD

**Issue by nap14hockey** [kanersps/esplugin_mysql#14]
When attempting to use the money system, the plugin does, in fact, store the money into the database, however upon retrieval, or upon using bank: withdraw, the money is 0, 0.  Therefore, the money HUD does not work, and other plugins that withdraw or give money to a player don't work.  ES_Admin however, does store the money correctly.

**Comment by ghost** [comment]
I am facing the same issue, except that ES_admin doesn't work well for me, too

**Comment by pavpd** [comment]
helpful as always :) btw for those looking for an answer es_extended ditched essentialmode so you can consider reverting to a version of esx before 17 february

**Comment by kanersps** [comment]
If there is need for this issue to be re-opened, let me know
