### ISSUE TITLE
MySQL error on login

### ISSUE THREAD

**Issue by ghost** [kanersps/esplugin_mysql#15]
[ERROR] [MySQL] [esplugin_mysql] An error happens on MySQL for query "INSERT INTO users (identifier, money, bank, group, permission_level, license`) VALUES ('steam:11000010aa2d83f', 0, 0, 'user', 0, 'license:5dd957d37dd59ac5256b99a291f674b7f916d3b3');": ER_BAD_FIELD_ERROR: Unknown column 'money' in 'field list'
SCRIPT ERROR: @essentialmode/server/player/login.lua:13: attempt to index a boolean value (local 'user')

    ref (@essentialmode/server/player/login.lua:13)
    ref (@esplugin_mysql/server.lua:20)
    (@mysql-async/mysql-async.js:14959) `

**Comment by kanersps** [comment]
Did you setup the correct .sql file or use fxmigration?

**Comment by ghost** [comment]
I use fxmigration

**Comment by kanersps** [comment]
Then how does your sql database look and is there any odd console output?

**Comment by ghost** [comment]
https://imgur.com/a/1ZRo2eG

https://pastebin.com/ZhidXvmV

I hope this is what you ask for

**Comment by ghost** [comment]
I thought this might help.

https://pastebin.com/SzDn9GTS

**Comment by jeanmarcs10200** [comment]
Hey did you manage to solve this?

**Comment by Sebbl0508** [comment]
OH my god i have this issue too, any solution
