### ISSUE TITLE
MySQL Error when join the server.

### ISSUE THREAD

**Issue by ghost** [kanersps/esplugin_mysql#17]
I saw someone with the same issue, but I cant resolve it with that comments and pictures.

[ERROR] [MySQL] [esplugin_mysql] An error happens on MySQL for query "INSERT INTO users (identifier, money, bank, group, permission_level, license`) VALUES ('steam:11000010aa2d83f', 0, 0, 'user', 0, 'license:5dd957d37dd59ac5256b99a291f674b7f916d3b3');": ER_BAD_FIELD_ERROR: Unknown column 'money' in 'field list'
SCRIPT ERROR: @essentialmode/server/player/login.lua:13: attempt to index a boolean value (local 'user')

ref (@essentialmode/server/player/login.lua:13)
ref (@esplugin_mysql/server.lua:20)
(@mysql-async/mysql-async.js:14959)
 `
https://prnt.sc/se45qn

I have no errors when I start the server. Only these errors when joining

server.cfg
https://pastebin.com/gWtCM7Qi

database:
https://prnt.sc/se47x2

User table
https://prnt.sc/se489d

**Comment by ThatGuyJacobee** [comment]
I have the exact same issue, literally all the errors are exactly the same and same thing happens when a new player joins. If any logs are needed from my side feel free to ask.

**Comment by kanersps** [comment]
You're on an unsupported version of ESX. I advise rolling back to 1.1, using ZAP's ESX version or utilizing ExtendedMode.

**Comment by woutvos** [comment]
I also have exactly the same error and I have tryed es_extended 1 but that didnt work.

**Comment by woutvos** [comment]
I know a fix. I had installed essentialmode but that is replaed by ESX so you need to delete that.
I want to give credits of solution to https://forum.cfx.re/u/bulva2/summary.
link to my forum about this https://forum.cfx.re/t/error-attempt-to-index-a-nil-value/1308247
