### ISSUE TITLE
Money not updating in DB

### ISSUE THREAD

**Issue by azarathkhan** [kanersps/esplugin_mysql#19]
Money is not updating for me in the users table due to esplugin_mysql.
I traced it to being an issue in server.lua "if (#new ~= 0)".
I added a print(#new) and found my new is always a length of 0 even though I new changes to push to the DB.

Any idea why this is happening? For now I am commenting out the if statement.

**Comment by azarathkhan** [comment]
I'd like to add that I am also running the newest essentialmode.

**Comment by Tinky124** [comment]
Same problem @azarathkhan money doesnt update i tested and old version working lastest doesnt work esplugin_mysql

**Comment by FlawwsX** [comment]
#20 Might help resolve the issue.
